# Generated by Django 4.1 on 2023-12-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
