# Generated by Django 4.1 on 2023-12-01 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_livro_pictures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
