# Generated by Django 4.1 on 2023-12-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
