# Generated by Django 4.1 on 2023-12-02 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('books', '0004_alter_pessoa_nome_delete_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('author', models.CharField(max_length=50, verbose_name='Autor')),
                ('sinopse', models.TextField(max_length=100, verbose_name='Sinopse')),
                ('date_fabrication', models.DateField(verbose_name='Data Fabricacao')),
                ('is_active', models.BooleanField(choices=[(True, 'Disponível'), (False, 'Indisponível')], default=False, verbose_name='Ativo')),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['id'],
            },
        ),
    ]
