# Generated by Django 4.1 on 2023-12-02 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_pessoa_nome_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.RemoveField(
            model_name='books',
            name='date_fabrication',
        ),
        migrations.RemoveField(
            model_name='books',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='books',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='books',
            name='sinopse',
        ),
    ]
