# Generated by Django 4.1 on 2023-12-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_books_category_remove_books_date_fabrication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Disponível'), (False, 'Indisponível')], default=False, verbose_name='Ativo'),
        ),
    ]
