# Generated by Django 4.1 on 2023-12-02 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_books_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='is_active',
        ),
    ]
